version: "3"

services:
  postgres:
       image: "postgres:11"
       ports:
         - "5432:5432"
       volumes:
         - postgres:/var/lib/postgresql/data
  app:
    environment:
      LC_ALL: C.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
    container_name: quickorder_backend
    depends_on:
         - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/quickorder
      - app-gems:/app-gems
    # env_file:
    #   - ".env"

volumes:
  postgres:
  app-gems:
