meta_product_name: "Quick Order"
meta_title: "Quick Order - Uma forma rápida e eficiente para o seu negócio."
meta_description: "Quick Order é uma plataforma para restaurantes que auxilia de forma tecnológica na realização dos pedidos. Podendo acompanhar os pedidos em fila, andamento, concluído e cancelados. O administrador através de seu dashboard poderá ver toda a movimentação do restaurante por dias, lucro diário e todos os pedidos e por atendentes."
meta_image: "quickorder.jpeg"
twitter_account: "@product_twitter_account"